/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI_workers;

import GUI.*;
import DataBase.DBMS;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author 3c tech
 */
public class payment_worker extends javax.swing.JFrame {

    public payment_worker() {

        initComponents();
         ImageIcon i1=new ImageIcon("src/Resorces/1-Normal-Paper-Box-icon_1.png");
        this.setIconImage(i1.getImage());

        TableModel tm = jTable1.getModel();
        DefaultTableModel dtf = (DefaultTableModel) tm;
        dtf.setRowCount(0);

        try {

            ResultSet rs = DBMS.SE("select * from grn_product");

            while (rs.next()) {

                Vector v = new Vector();

                v.add(rs.getString("grn_id"));

                ResultSet rs1 = DBMS.SE("select brand_id from product where id='" + rs.getString("product_id") + "'   ");
                if (rs1.next()) {

                    ResultSet rs2 = DBMS.SE("select name from brand where id='" + rs1.getString("brand_id") + "'");

                    if (rs2.next()) {
                        v.add(rs2.getString("name"));
                    }

                }

                ResultSet rs3 = DBMS.SE("select name from product where id='" + rs.getString("product_id") + "'   ");

                if (rs3.next()) {
                    v.add(rs3.getString("name"));

                }

                v.add(rs.getString("qty"));
                v.add(rs.getString("buying_price"));

                String s = rs.getString("qty");
                String s1 = rs.getString("buying_price");
                double b1 = Double.parseDouble(s);
                double b2 = Double.parseDouble(s1);
                double total = b1 * b2;

                String ts=String.valueOf(total);
                v.add(ts);

                String s2 = "";

                ResultSet rs4 = DBMS.SE("select * from grn where id='" + rs.getString("grn_id") + "'   ");

                while (rs4.next()) {
                    v.add(rs4.getString("paid_amount"));
                    s2 = rs4.getString("paid_amount");
                }

                double b3 = Double.parseDouble(s2);

                double x1 = total - b3;
                String x=String.valueOf(x1);
                

                v.add(x);

                ResultSet rs5 = DBMS.SE("select * from grn where id='" + rs.getString("grn_id") + "'");

                while (rs5.next()) {
                    v.add(rs5.getString("suppliar_mobile"));
                    v.add(rs5.getString("date"));
                }

                dtf.addRow(v);

            }

        } catch (Exception e) {
            System.out.println(e);
        }

        try {

            int row = jTable1.getRowCount();

            for (int i = 0; i < row; i++) {

                String s = (String) jTable1.getValueAt(i, 0);

                if (row > i + 1) {

                    if (s.equals(jTable1.getValueAt(i + 1, 0))) {

                        ResultSet rs11 = DBMS.SE("select qty,buying_price from grn_product where grn_id='" + s + "'");

                        double b4 = 0.0;
                        while (rs11.next()) {

                            double b = rs11.getDouble("qty");
                            double b1 = rs11.getDouble("buying_price");

                            double b3 = b * b1;
                            b4 = b4 + b3;

                        }

                        ResultSet rs12 = DBMS.SE("select paid_amount from grn where id='" + s + "'");
                        double bb = 0.0;
                        if (rs12.next()) {

                            double b5 = rs12.getDouble("paid_amount");
                            bb = b4 - b5;

                        }
                        String balance=String.valueOf(bb);
                        jTable1.setValueAt(balance, i, 7);
                        jTable1.setValueAt(balance, i + 1, 7);

                    }
                }

            }

        } catch (Exception e) {

            System.out.println(e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Brand", "Product", "Qty", "Buying price", "Total", "Paid Amount", "Balance", "Supliar", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 820, 750));

        jButton2.setBackground(new java.awt.Color(51, 0, 51));
        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 204, 0));
        jButton2.setText("Print");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 590, 500, 170));

        jLabel4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("SETTLE PAYMENT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 10, 220, 50));

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(51, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/CloseAndMinimize/minimize (1).png"))); // NOI18N
        jButton7.setBorder(null);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 40, 40));

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 0, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/CloseAndMinimize/cancel (1).png"))); // NOI18N
        jButton6.setBorder(null);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusable(false);
        jButton6.setPreferredSize(new java.awt.Dimension(15, 19));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 40));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/CloseAndMinimize/iconfinder_Open_v2_131829.png"))); // NOI18N
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 10, 40, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settle Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Supliar");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, 100, 30));

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField4KeyReleased(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 470, 40));

        jLabel14.setBackground(new java.awt.Color(255, 255, 0));
        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 204, 0));
        jLabel14.setText("........................");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 160, 30));

        jLabel12.setBackground(new java.awt.Color(255, 255, 0));
        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 204, 0));
        jLabel12.setText(".......................");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 160, 30));

        jTextField11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        jTextField11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField11KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 360, 60));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setFont(new java.awt.Font("Sylfaen", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 204, 102));
        jButton1.setText("Pay");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.white, java.awt.Color.white));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 380, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 204, 102), new java.awt.Color(0, 204, 102)), "Payment", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 1, 18), new java.awt.Color(0, 204, 102))); // NOI18N
        jPanel2.setOpaque(false);

        jLabel18.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 204, 102));
        jLabel18.setText("Payment");
        jPanel2.add(jLabel18);

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 400, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 70, 510, 500));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resorces/149795.jpg"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        TableModel tm=jTable1.getModel();
       
        payment_report pr=new payment_report(tm);
        pr.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jTextField11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyReleased

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        this.setState(Home.ICONIFIED);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyReleased
        String sq=jTextField4.getText();
        
        try {
            
            TableModel tm=jTable1.getModel();
            DefaultTableModel df=(DefaultTableModel) tm;
            df.setRowCount(0);
            
            
            ResultSet rs=DBMS.SE("select * from grn_product where grn_id in(select id from grn where suppliar_mobile like '%"+sq+"%')");
            
        
        while (rs.next()) {  
            Vector v=new Vector();
            
            v.add(rs.getString("grn_id"));
            
            
            
              ResultSet rs1 = DBMS.SE("select brand_id from product where id='" + rs.getString("product_id") + "'   ");
                if (rs1.next()) {

                    ResultSet rs2 = DBMS.SE("select name from brand where id='" + rs1.getString("brand_id") + "'");

                    if (rs2.next()) {
                        v.add(rs2.getString("name"));
                    }

                }
            
                ResultSet rs3 = DBMS.SE("select name from product where id='" + rs.getString("product_id") + "'   ");

                if (rs3.next()) {
                    v.add(rs3.getString("name"));

                }

                v.add(rs.getString("qty"));
                v.add(rs.getString("buying_price"));

                String s = rs.getString("qty");
                String s1 = rs.getString("buying_price");
                double b1 = Double.parseDouble(s);
                double b2 = Double.parseDouble(s1);
                double total = b1 * b2;
                

                 String ts=String.valueOf(total);
                v.add(ts);
                
                

                String s2 = "";

                ResultSet rs4 = DBMS.SE("select * from grn where id='" + rs.getString("grn_id") + "'   ");

                while (rs4.next()) {
                    v.add(rs4.getString("paid_amount"));
                    s2 = rs4.getString("paid_amount");
                }

                double b3 = Double.parseDouble(s2);

                double x1 = total - b3;
                
                String x=String.valueOf(x1);

                v.add(x);

                ResultSet rs5 = DBMS.SE("select * from grn where id='" + rs.getString("grn_id") + "'");

                while (rs5.next()) {
                    v.add(rs5.getString("suppliar_mobile"));
                    v.add(rs5.getString("date"));
                }
            
            df.addRow(v);
            
        }
        
         try {

            int row = jTable1.getRowCount();

            for (int i = 0; i < row; i++) {

                String s = (String) jTable1.getValueAt(i, 0);

                if (row > i + 1) {

                    if (s.equals(jTable1.getValueAt(i + 1, 0))) {

                        ResultSet rs11 = DBMS.SE("select qty,buying_price from grn_product where grn_id='" + s + "'");

                        double b4 = 0.0;
                        while (rs11.next()) {

                            double b = rs11.getDouble("qty");
                            double b1 = rs11.getDouble("buying_price");

                            double b3 = b * b1;
                            b4 = b4 + b3;

                        }

                        ResultSet rs12 = DBMS.SE("select paid_amount from grn where id='" + s + "'");
                        double bb = 0.0;
                        if (rs12.next()) {

                            double b5 = rs12.getDouble("paid_amount");
                            bb = b4 - b5;

                        }

                       String balance=String.valueOf(bb);
                        jTable1.setValueAt(balance, i, 7);
                        jTable1.setValueAt(balance, i + 1, 7);

                    }
                }

            }

        } catch (Exception e) {

            System.out.println(e);
        }
            
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
  
        
        
    }//GEN-LAST:event_jTextField4KeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = jTable1.getSelectedRow();
        String s = (String) jTable1.getValueAt(i, 0);
        try {
            double b = 0.0;
            ResultSet rs = DBMS.SE("select paid_amount from grn where id='" + s + "'");
            if (rs.next()) {
                b = rs.getDouble("paid_amount");

            }

            String s1 = jTextField11.getText();
            double b1 = Double.parseDouble(s1);

            double total = b + b1;

            DBMS.i("Update grn set paid_amount='" + total + "' where id='" + s + "'");
            this.dispose();
            payment_worker p=new payment_worker();
            p.setVisible(true);

        } catch (Exception e) {
            System.out.println(e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int i=jTable1.getSelectedRow();
       String s1=(String) jTable1.getValueAt(i, 8);
        String s2= (String) jTable1.getValueAt(i, 7);
        
        
       jLabel14.setText(s1);
       jLabel12.setText(s2);
       
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
       GRN_worker g=new GRN_worker();
       g.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jTextField11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField11KeyTyped
char c=evt.getKeyChar();
        if (Character.isLetter(c)) {
            evt.consume();}        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payment_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payment_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payment_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payment_worker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payment_worker().setVisible(true);

            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

}
